- name: Install resolvconf
  apt: name=resolvconf state=present

- name: Copy base for resolvconf
  template:
    src: base
    dest: "/etc/resolvconf/resolv.conf.d/base"

- name: Update resolv.conf
  become: yes
  command: resolvconf -u

- name: Disable systemd-resolved
  become: yes
  command: systemctl disable systemd-resolved.service

- meta: flush_handlers

- name: install dnsmasq
  apt: name=dnsmasq state=present

- name: "setup"
  template:
    src: main.conf
    dest: "/etc/dnsmasq.d/main.conf"
  notify: restart dnsmasq